### ISSUE TITLE
rename repository

### ISSUE THREAD

**Issue by kortschak** [carp-te/carp-documentation#1]
Biogo document is not informative, I would suggest "carp-annotation" or something like that.

/cc @dadelson

**Comment by luzengAdelaide** [comment]
Yeah, I agree with that! It's not the right name


--
Lu Zeng
PhD Candidate in Bioinformatics
School of Biological Sciences
The University of Adelaide

Level 2 Braggs Building
North Terrace, Adelaide SA
Australia 5005

Phone: 08 8313 1022
LinkedIn: www.linkedin.com/in/<http://www.linkedin.com/in/>luzengBioinformatcis
Twitter: @sophieluzeng
________________________________

**Comment by dadelson** [comment]
I suggest **CARP Documentation** as the repo name.

**Comment by luzengAdelaide** [comment]
Done
