### ISSUE TITLE
Propagating revisions in this document to the PLoS ONE supplementary material

### ISSUE THREAD

**Issue by dadelson** [carp-te/carp-documentation#12]
@luzengAdelaide  @kortschak Are any of the changes you made to this repo things that need to be changed in the Supplementary material document from the PLoS ONE paper?  It is probably worth putting the URL for this project into the Supplementary material document with a statement to the effect that for up to date versions of the documentation and code people should go here.

**Comment by kortschak** [comment]
>It is probably worth putting the URL for this project into the Supplementary material document with a statement to the effect that for up to date versions of the documentation and code people should go here.

SGTM
