### ISSUE TITLE
pdf document name mis-spelled

### ISSUE THREAD

**Issue by kortschak** [carp-te/carp-documentation#2]
This will need a `git mv` for both the pdf and the tex. While you are at it, also shorten it and remove the spaces in the filename.

**Comment by dadelson** [comment]
@luzengAdelaide Can we get this done?  If this is a public repo it needs to look professional.

**Comment by dadelson** [comment]
@luzengAdelaide The spelling of the file name still needs to be corrected: document, not documnet.

**Comment by luzengAdelaide** [comment]
@dadelson We made all the changes in a branch called fixes, we renamed document name to CARP

**Comment by kortschak** [comment]
This is fixed in #6.

**Comment by dadelson** [comment]
![documnet_screen_grab](https://user-images.githubusercontent.com/13565566/35495136-51221b6e-050f-11e8-995d-5ad23f0a1814.png)
This what it looks like right now.

**Comment by luzengAdelaide** [comment]
@kortschak Should we rebase and merge it?

**Comment by luzengAdelaide** [comment]
@dadelson merged now!

**Comment by dadelson** [comment]
That’s better.

**Comment by luzengAdelaide** [comment]
Done
